### PR TITLE
updating to latest graphviz

### PR DESCRIPTION
**Pull request by paul90**
- adds build step to include graphviz
  latest version of @hpcc-js/wasm either loads via CDN to needs a build step to include the WASM. Rather than using a CDN, here I use the npm package, and use esbuild to bundle it all together - run `npm run build`.

- removes double render() call.
  this appears to be part of the problem causing graphviz to not render, at least sometime. There still appears to be a problem in the client that causes bind to be called multiple time.

### CODE REVIEW

**Comment by paul90** [comment]
I'm in two minds about adding the generated bundle `client/graphviz-view.js` and its map file to gitignore.

**Comment by dobbs** [comment]
My other thought this many years later... the custom element is creating complexity and I don't think we've gotten any use from the separation of concerns.

Contrast the custom element here with Observable's use of a tagged template:
https://github.com/observablehq/graphviz/blob/master/index.js
(docs on tagged templates: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates)

Every time I look at Observable's graphviz I find myself double-checking their dependency on the viz.js library and feel reassured that it has been getting new attention in the past couple years.
https://github.com/mdaines/viz-js/graphs/contributors

We could remove the custom element and instead take a dependency on Observable's tagged template wrapper and the transitive dependency on viz.js and the related build machinery.

**Comment by paul90** [comment]
That would be good, we are using Observable's D3 over in the data graph plugin.

**Comment by WardCunningham** [comment]
I'm having trouble understanding https://github.com/observablehq/graphviz/blob/master/index.js.
Where in this code does it run the WASM Graphviz?
I would be expecting one-line:
`hpccWasm.graphviz.layout(dot, "svg", "dot").then(svg => ...)`
Of course we would expect some preprocessing the dot and maybe post-processing the svg.
Isn't most of the template machinery user-facing where we use editable items for this?

**Comment by WardCunningham** [comment]
Thank you. I will dig into this again tomorrow.

**Comment by dobbs** [comment]
Just published https://github.com/fedwiki/wiki-plugin-graphviz/tree/v0.11.5 which includes removal of the custom element and a switch to using viz-js.

With this change I've also transferred the plugin to fedwiki.

**Pull request closed without merging**
